### Importing Required Packages

In [251]:
import numpy as np

#to prevent numpy from using scientific notation, make the line 100 in width, take only 2 digits after the decimal
np.set_printoptions(suppress  = True, linewidth = 100, precision = 2)

### Importing Bank Loans Dataset

In [252]:
loan_data = np.genfromtxt("loan-data.csv", delimiter = ";" , skip_header = 1, autostrip = True)
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Checking for Missing Values

In [253]:
#finding the number of NAN values
np.isnan(loan_data).sum()

88005

In [254]:
#finding the fill_value which will substitute NAN values by finding the maximum value of each column + 1
fill_value = np.nanmax(loan_data) + 1

#finding the mean of each column
temporary_mean = np.nanmean(loan_data, axis = 0)
temporary_mean

# the mean of a column that contains only strings will be filled with NAN values and considered empty 

C:\Users\aa10098\AppData\Local\Temp/ipykernel_8256/455305190.py:5: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(loan_data, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [255]:
#finding the minimum value, mean, and maximum value of each column
temporary_stats = np.array([np.nanmin(loan_data, axis = 0), temporary_mean, np.nanmean(loan_data, axis = 0)])
temporary_stats

C:\Users\aa10098\AppData\Local\Temp/ipykernel_8256/2562941271.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(loan_data, axis = 0), temporary_mean, np.nanmean(loan_data, axis = 0)])
C:\Users\aa10098\AppData\Local\Temp/ipykernel_8256/2562941271.py:2: RuntimeWarning: Mean of empty slice
  temporary_stats = np.array([np.nanmin(loan_data, axis = 0), temporary_mean, np.nanmean(loan_data, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85]])

### Splitting the Dataset

In [256]:
#returning the indices of columns that contain completely strings 
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings 

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [257]:
#returning the indices of columns that contain completely numbers
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

#### Re-importing the splitted dataset

In [258]:
# String Data
loan_data_string = np.genfromtxt("loan-data.csv",
                                  delimiter = ';',
                                  skip_header = 1,
                                  autostrip = True, 
                                  usecols = column_strings,
                                  dtype = np.str)
loan_data_string

C:\Users\aa10098\AppData\Local\Temp/ipykernel_8256/4137566773.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [259]:
# Numeric Data
loan_data_numeric = np.genfromtxt("loan-data.csv",
                                 delimiter = ";",
                                 skip_header = 1,
                                 autostrip = True,
                                 usecols = column_numeric,
                                 filling_values = fill_value)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

#### Naming the Two Data Subsets Columns

In [260]:
# Getting names of all columns 
header_full = np.genfromtxt("loan-data.csv",
                           delimiter = ";",
                           autostrip = True,
                           skip_footer = loan_data.shape[0],
                           dtype = np.str)
header_full

C:\Users\aa10098\AppData\Local\Temp/ipykernel_8256/3579077447.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [261]:
# Getting names of string columns and numeric columns
header_string, header_numeric = header_full[column_strings], header_full[column_numeric]

In [262]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [263]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Creating Checkpoint

In [264]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [265]:
checkpoint_test = checkpoint("checkpoint-test", header_string, loan_data_string)

In [266]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Manipulating String Columns

#### Issue Date 

In [267]:
# removing the year next to each month
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], "-15") 
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [268]:
# Converting month name into integer
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
                                    i, 
                                    loan_data_string[:,0]) 
loan_data_string[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

#### Loan Status

In [269]:
loan_data_string[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [270]:
# creating an array for bad status 
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [271]:
# Converting string status into numeric: 0 for bad, and 1 for good status
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], status_bad),0,1)

In [272]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

#### Term

In [273]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [274]:
# Removing months part of each value in the Term column
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], "months")
np.unique(loan_data_string[:,2])

array(['', '36 ', '60 '], dtype='<U69')

In [275]:
# Substituting the missing values with 60 (the worst case scenario)
loan_data_string[:,2] = np.where(loan_data_string[:,2] == '', 
                                  '60', 
                                  loan_data_string[:,2])
np.unique(loan_data_string[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

#### Grade & Subgrade

In [276]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [277]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Subgrades

In [278]:
# filling wrong values in Subgrade 
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                      i + '5',
                                      loan_data_string[:,4])

In [279]:
# Substituting missing values in Subgrade
loan_data_string[:,4] = np.where(loan_data_string[:,4] == '',
                                  'H1',
                                  loan_data_string[:,4])

#### Removing Grade Column

In [280]:
loan_data_string = np.delete(loan_data_string, 3, 1)
header_string = np.delete(header_string, 3)

#### Converting Subgrade

In [281]:
np.unique(loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [282]:
# creating a dictionary with numeric values for string keys of subgrades
keys = list(np.unique(loan_data_string[:,3]))                         
values = list(range(1, np.unique(loan_data_string[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

In [283]:
for i in np.unique(loan_data_string[:,3]):
        loan_data_string[:,3] = np.where(loan_data_string[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_string[:,3])
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Verification Status

In [284]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [285]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') | (loan_data_string[:,4] == 'Not Verified'), 0, 1)

In [286]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

#### URL

In [287]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [288]:
# removing the link part of the URL
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [289]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [290]:
# The URL contains the loan id which is already exists in id column
loan_data_string = np.delete(loan_data_string, 5, axis = 1)
header_string = np.delete(header_string, 5)

In [291]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

#### Address State

In [292]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [293]:
# dividing states into two arrays (each state name and its count)
states_names, states_count = np.unique(loan_data_string[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [294]:
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '', 
                                  0, 
                                  loan_data_string[:,5])

In [295]:
# dividing states into 4 arrays according to its location
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [296]:
# giving the states in each direction a certain integer for simplification
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [297]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting String Data into Numeric

In [298]:
loan_data_string

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [299]:
loan_data_string.astype(int)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

#### Checkpoint 1 - String Data

In [300]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_string, loan_data_string)

In [301]:
checkpoint_strings["header"]

array(['issue_d', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [302]:
checkpoint_strings["data"]

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [303]:
np.array_equal(checkpoint_strings['data'], loan_data_string)

True

### Numeric Data Manipulation 

In [304]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [305]:
np.isnan(loan_data_numeric).sum()

0

### Substitute Filler Values

#### ID

In [306]:
np.isnan(loan_data_numeric[:,0]).sum()

0

#### Temporary Stats (min, mean, max)

In [307]:
temporary_stats[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85]])

#### Funded Amount

In [308]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [309]:
# substitute the missing values (substituted before by fill value) with the minimum funded amount
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == fill_value, 
                                  temporary_stats[0, column_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [310]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == fill_value,
                                      temporary_stats[2, column_numeric[i]],
                                      loan_data_numeric[:,i])

In [311]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       16.62,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       16.62,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       16.62,      440.92,     2185.64],
       [46154151.  ,    15273.46,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       16.62,      309.97,      301.9 ]])

### Checkpoint 2 for Numeric Data

In [312]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [313]:
checkpoint_numeric['header']

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [314]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       16.62,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       16.62,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       16.62,      440.92,     2185.64],
       [46154151.  ,    15273.46,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       16.62,      309.97,      301.9 ]])

### Creating the Complete DataSet

In [315]:
checkpoint_numeric['data'].shape


(10000, 6)

In [316]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [317]:
loan_data

array([['48010226.0', '35000.0', '35000.0', ..., '13', '1', '1'],
       ['57693261.0', '30000.0', '30000.0', ..., '5', '1', '4'],
       ['59432726.0', '15000.0', '15000.0', ..., '10', '1', '4'],
       ...,
       ['50415990.0', '10000.0', '10000.0', ..., '5', '1', '1'],
       ['46154151.0', '15273.463157894737', '10000.0', ..., '17', '1', '3'],
       ['66055249.0', '10000.0', '10000.0', ..., '4', '0', '3']], dtype='<U69')

In [318]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))
header_full

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'issue_d',
       'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

### Sorting the Complete Data Set

In [319]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([['12606806.0', '24975.0', '24975.0', ..., '10', '1', '2'],
       ['13026045.0', '12000.0', '12000.0', ..., '13', '1', '2'],
       ['1312426.0', '15000.0', '15000.0', ..., '16', '1', '4'],
       ...,
       ['8138291.0', '10350.0', '1000.0', ..., '26', '1', '4'],
       ['8214572.0', '7000.0', '7000.0', ..., '11', '1', '2'],
       ['849994.0', '11400.0', '11400.0', ..., '10', '0', '1']], dtype='<U69')

### Storing The Complete Data Set

In [320]:
loan_data = np.vstack((header_full, loan_data))

In [321]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')